# -*- coding: utf-8 -*-
"""fase6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y22k3MkTvneE5HXThwCmYyoxhwPpPqtV

# 1. Montando o Google Drive no Colab para que possamos acessar os arquivos armazenados lá, como as imagens e os rótulos.
"""

from google.colab import drive
drive.mount('/content/drive')

"""# 2. Clonando o repositório oficial do YOLOv5, para que possamos usar os scripts necessários para treinar o modelo."""

! git clone https://github.com/ultralytics/yolov5.git

"""# 3. Instalando as dependências do YOLOv5
# Este comando instala todas as bibliotecas necessárias que o YOLOv5 usa, como o PyTorch, OpenCV e outras dependências importantes.
"""

! pip install -r yolov5/requirements.txt

"""# 4. Treinando o modelo YOLOv5
# Agora, vamos treinar o modelo usando o arquivo `trator.yaml` (que contém o caminho para as imagens e rótulos), com 40 epochs e imagens de tamanho 640x640.
"""

!python yolov5/train.py --data /content/drive/MyDrive/FarmTechProjeto/trator.yaml --weights yolov5s.pt --img 640 --epochs 40

"""# 5. Validação do modelo
# O comando abaixo realiza a validação com o melhor modelo treinado, usando o arquivo de validação.


"""

!python yolov5/val.py --weights yolov5/runs/train/exp/weights/best.pt --data /content/drive/MyDrive/FarmTechProjeto/trator.yaml --img 640

"""# 7. Treinamento com 60 epochs para comparar com o de 40 epochs

"""

!python yolov5/train.py --data /content/drive/MyDrive/FarmTechProjeto/trator.yaml --weights yolov5s.pt --img 640 --epochs 60 --name treino_60epocas

"""# 8. Teste do modelo"""

!python yolov5/detect.py --weights yolov5/runs/train/treino_60epocas/weights/best.pt --img 640 --conf 0.4 --source /content/drive/MyDrive/FarmTechProjeto/test/images